### ISSUE TITLE
Broken 'About Us' Link

### ISSUE THREAD

**Issue by matt-ross16** [codestromer/ContestReminder#12]
There is a broken `About Us` link on the Home page. 

![image](https://user-images.githubusercontent.com/37879416/101670020-acf47b00-3a20-11eb-97f5-d0b1a98f6ef0.png)

Now that an `About` button has been added to the layout, the `About Us` link may be redundant.

**Comment by akshitdesai** [comment]
1) Remove the About us button.
2) Rename 'About us' as 'Contributors' and give that link to /about.
Did you get it?

**Comment by matt-ross16** [comment]
Ok I'll handle this swap. On another note, what is intended for the `Report Bug/Send Feedback` link? Right now it just points back to the Home page

**Comment by akshitdesai** [comment]
Remove "send feedback", and report Bug should redirect to the issue page of this Repo.

**Comment by matt-ross16** [comment]
Ok I'll file another issue for the other link and take care of that as well

**Comment by matt-ross16** [comment]
Would you like the `About` heading to be removed or replaced by something else?

![image](https://user-images.githubusercontent.com/37879416/101829854-a8ec5a00-3b01-11eb-819e-8545cbf5d5e6.png)

**Comment by akshitdesai** [comment]
Ye Remove that and then create a PR.
