### ISSUE TITLE
Add contributor page using github api

### ISSUE THREAD

**Issue by akshitdesai** [codestromer/ContestReminder#5]
In about page list contributors of this repository using GitHub API. Try to initiate the work. Improvements can be done later.

**Comment by akshitdesai** [comment]
API URL for our project:- https://api.github.com/repos/codestromer/ContestReminder/contributors

**Comment by matt-ross16** [comment]
I'd like to try to get this running for you

**Comment by akshitdesai** [comment]
Ok, Sure!! Go for it.

**Comment by matt-ross16** [comment]
For the about page, where are you hoping to have this featured? Prior to logging in, or only after authentication?

I considered placing it as a template, but wanted to see what you preferred

**Comment by akshitdesai** [comment]
Ya, place it as a template.

**Comment by matt-ross16** [comment]
Ok, this is what I have so far: 

![image](https://user-images.githubusercontent.com/37879416/101390540-fdd56980-3890-11eb-917d-535e24175cc7.png)

The profile pictures are clickable and open a new tab for the user's profile page, and then I have the username and the number of contributions they've made listed.

Formatting could be improved, but thought I'd take suggestions on that!

**Comment by matt-ross16** [comment]
Here's the commit so far:
https://github.com/matt-ross16/ContestReminder/commit/5b8919d392367217b408f9285c2841c3ad4e02c4

**Comment by matt-ross16** [comment]
New look! 

![image](https://user-images.githubusercontent.com/37879416/101398869-b8b73480-389c-11eb-9621-507717c7bf60.png)

Hovering over the profile images will provide the username and the number of contributions rather than clogging up the screen with the info

**Comment by akshitdesai** [comment]
Thank you!! @matt-ross16
